### ISSUE TITLE
add snackbar and functionality to the like and download button 

### ISSUE THREAD

**Issue by sahilrik** [DSCKGEC/Wallx#4]
on tapping the like button it should change the state of the button (to a liked state eg - from a hollow outlined to a filled button) and show a snack bar with a message.

on tapping the download button it should download the image (u should be able to find the image in the gallery) and show a snack bar with the message "image successfully downloaded".

**Comment by Adiii1436** [comment]
I want to work on this issue.

**Comment by sahilrik** [comment]
hey @Adiii1436 the issue is assigned to you
